version: '2'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    ports:
      - "2223:22"
    links:
      - mysql:mysql
    volumes:
      - /usr/src/app/app/static
    env_file:
      - ./mysql/.after_build_env.env
      - ./web/.after_build_env.env
    depends_on:
        - mysql
    command: /bin/bash -c "sleep 10; /usr/bin/supervisord"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
    command: /usr/sbin/nginx

  mysql:
    restart: always
    image: mysql:5.7.16
    env_file: ./mysql/.after_build_env.env


#http://containertutorials.com/docker-compose/nginx-flask-postgresql.html
